<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <title>SwapHub</title>
</head>
<body>
<nav class="navbar navbar-custom">
    <div class="container-fluid">
        <a href="/">
            <span class="navbar-brand mb-0 h1">SwapHub</span>
        </a>
    </div>
</nav>
<h1 style="width: 100%;">Go back.</h1>
</body>
</html>